language: csharp
mono: none
dist: trusty
dotnet: 2.0.0
solution: CNSubtitles.sln
install:
- dotnet restore
script:
- dotnet build -c Release
deploy:
  provider: releases
  file_glob: true
  file: emby_cn_sub/bin/Release/*/Emby.cn.sub.dll
  skip_cleanup: true
on:
  repository_dispatch:
  release:
    types: published
  push:
    branches:
      - master

#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: started
